image: docker:stable

services:
- docker:dind 

before_script:
- docker info
- pip install docker-compose
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
  stage: build
  script:
  - docker-compose -f docker-compose.yml build