version: '3.4'
services:
  db: 
    image: joelmarcos/mysql-rest-with-spring-boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:  
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot
    ports: 
      - "3308:3306"
    networks:
      - cardoso-networks
  rest-with-spring-boot:
    image: joelmarcos/rest-with-spring-boot
    restart: always
    build: ./restwithspringboot
    working_dir: /restwithspringboot
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./restwithspringboot:/restwithspringboot
      - ~/.m2:/root/.m2
    ports: 
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks: 
      - cardoso-networks
networks:
  cardoso-networks:
    driver: bridge
