version: '3.4'
services:
  db: 
    image: joelmarcos/mysql-help-desk-security
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:  
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: help-desk-security
    ports: 
      - "3308:3306"
    networks:
      - cardoso-networks
  help-desk-security:
    image: joelmarcos/help-desk-security
    restart: always
    build: help-desk-security
    working_dir: help-desk-security
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./helpDeskSecurity:/helpDeskSecurity
      - ~/.m2:/root/.m2
    ports: 
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks: 
      - cardoso-networks
networks:
  cardoso-networks:
    driver: bridge
