spring: 
  datasource: 
    password: admin
    url: "jdbc:mysql://localhost:3306/help_desk_security?useTimezone=true&serverTimezone=UTC"
    username: root
  jpa: 
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
    show-sql: true

check-user-scopes: true
